### ISSUE TITLE
Web Panel not allowing remote execution nor showing running servers

### ISSUE THREAD

**Issue by Gerald12344** [Epix-Incorporated/Adonis#373] opened 2021-06-20 18:08 UTC
I have been using Adonis web panel for a couple months, no changes to my API key or the game's code. The web panel doesn't show any running servers except for studio games, however other settings like admins (on web panel) and changing command permissions work perfectly.

-- Gerald

**Comment by froggisfriend** [comment] 2021-07-04 01:01
i have just noticed this aswell

**Comment by DavidBaszuckiA** [comment] 2021-07-04 22:12
Thanks for the follow-up! We have found the cause of the outage and will be resolving it shortly.
![image](https://user-images.githubusercontent.com/86933176/124400820-e5d5a380-dd14-11eb-9e1d-6ae5bcefaf43.png)

**Comment by GalacticInspired** [comment] 2021-07-04 22:15
https://discord.gg/QwZ6gSkX Please join this server to talk to the president of Customer Service, thanks,

**Comment by Gerald12344** [comment] 2021-07-08 17:56
Any luck, I am still not getting anything on my end. Is the web panel fully open source? Or is there someone I can speak to about this directly?

-- Gerald

**Comment by P3tray** [comment] 2021-07-08 18:12
Message Cald on Discord.

**Comment by P3tray** [comment] 2021-07-08 18:13
All my games are displayed
![image](https://user-images.githubusercontent.com/31691973/124970943-86330d00-e020-11eb-8935-53c827bf643f.png)

**Comment by Gerald12344** [comment] 2021-07-08 18:14
@P3tray same but it says zero members and zero servers

**Comment by P3tray** [comment] 2021-07-08 18:21
> 
> 
> @P3tray same but it says zero members and zero servers, when there are 40 players and 4 servers

My games don't have any players lol.

**Comment by gmoddev** [comment] 2021-12-01 03:10
> @P3tray same but it says zero members and zero servers, when there are 40 players and 4 servers

Did you setup the api key inside the adonis settings? if not you need to put `settings.WebPanel_Enabled = true;
settings.WebPanel_ApiKey = "";	` somewhere

**Comment by Gerald12344** [comment] 2021-12-01 07:25
> > @P3tray same but it says zero members and zero servers, when there are 40 players and 4 servers
> 
> 
> 
> Did you setup the api key inside the adonis settings? if not you need to put `settings.WebPanel_Enabled = true;
> 
> settings.WebPanel_ApiKey = "";	` somewhere

Yeah I did all that and it worked fine for a while then without any warning all my games stopped working. Now the web panel works for the first 30 seconds of the server then after that the server disappears from the web panel active servers.

**Comment by gmoddev** [comment] 2021-12-07 02:42
> Also having the same issue. Only studio test servers show up and if i try doing anything remote it just doesn't work.

I've had the same remote issue, but ive not really tested non studio servers, but as long as you setup everything right then you shoudlnt have a problem

**Comment by Deniied** [comment] 2021-12-07 17:32
Did you enable HTTPService? also I wouldn't recommend using Adonis' web panel it's a better idea to make your own or wait until the web panel is open source.

**Comment by coasterteam** [comment] 2021-12-07 17:40
Would also advise waiting too, the panel itself is rather buggy as it hasn't really been worked on since Feb 2021 as Calds been focused on the new panel. Myself and other devs not been able to see the actual currently web-panel code so we can't vet on it's security, but the new one is coming out in the next few weeks/months. Hopefully the new one will be open source so we can vet the code, but we'll see.

**Comment by DTJMdr** [comment] 2021-12-23 00:57
I'v also the same problem.

**Comment by DTJMdr** [comment] 2021-12-23 00:58
I'v the same problem.

_(someone have the discord of Adonis ?)_

**Comment by GalacticInspired** [comment] 2021-12-23 01:09
https://discord.gg/DB7FfEjZ

**Comment by DTJMdr** [comment] 2021-12-24 01:27
> https://discord.gg/DB7FfEjZ

Thx

**Comment by SyntaxEvasion** [comment] 2022-01-29 20:11
Cuh………

**Comment by SyntaxEvasion** [comment] 2022-01-29 20:13
![](https://c.tenor.com/g3Qqmjt1dbgAAAAC/cuh-old-man.gif)

**Comment by SyntaxEvasion** [comment] 2022-01-29 20:14
![003DC81B-FF04-46F9-8D34-501424D639C9](https://user-images.githubusercontent.com/96848089/151676198-4186b683-fd1e-4e5b-a334-c0ceb3ef49d9.gif)

**Comment by DaEnder** [comment] 2022-01-29 20:51
``

**Comment by LolloDev5123** [comment] 2022-03-17 16:51
I'm sorry why can't the webpanel just be opensource

**Comment by LolloDev5123** [comment] 2022-03-17 18:55
Ew react

**Comment by Gerald12344** [comment] 2022-03-17 20:20
nahhhhhhhh, react is great but I have been meaning to learn svelte

**Comment by Gerald12344** [comment] 2022-03-18 08:38
> Would also advise waiting too, the panel itself is rather buggy. It hasn't really been worked on since Feb 2021 as Calds been focused on the new panel. Myself and other devs not been able to see the actual currently web-panel code so we can't vet on it's security, but the new one is coming out in the next few weeks/months. Hopefully the new one will be open source so we can vet the code, but we'll see.

Any update on the release date?

**Comment by joritochip** [comment] 2022-04-05 04:13
Both Cald and I, the primary devs of the web panel, have been rather busy with school and whatnot. I am hopeful that we will be able to get a new version of the web panel out in the near future, hopefully in the next few months.

**Comment by Gerald12344** [comment] 2022-04-05 17:46
> Both Cald and I, the primary devs of the web panel, have been rather busy with school and whatnot. I am hopeful that we will be able to get a new version of the web panel out in the near future, hopefully in the next few months.

Is it possible to make it open source so we can chip in and help?

**Comment by GalacticInspired** [comment] 2022-04-05 17:47
Join the main discord server for better communications.

**Comment by Expertcoderz** [comment] 2022-06-21 14:20
It's been a literal year now. Has this been resolved?

**Comment by GalacticInspired** [comment] 2022-06-21 14:21
> It's been a literal year now. Has this been resolved?

ofc not

**Comment by LiveFireExercise** [comment] 2023-10-26 11:22
Webpanel is depracated; therefore we've fixed it. Well done gang! Time to take a well-deserved 5 year break.

**Closed by LiveFireExercise** 2023-10-26 11:22 UTC
Labels: 🐛 bug, sadface :(, 🌐 webpanel

**Comment by P3tray** [comment] 2023-10-30 09:14
Well done team. I'm going on vacation. This was a hard issue to crack.
