### ISSUE TITLE
Fly causes you to fall through the world to the void

### ISSUE THREAD

**Issue by ccuser44** [Epix-Incorporated/Adonis#1159] opened 2023-07-06 09:10 UTC
- To acomplish the bug you have to do `:fly`

- The normally expected result would be that fly would function properly.

- The actual result of the bug is that you falll to the void through the world.

- The impact of this bug is that `:fly` is totally unusable.

- This happens at least on the nightly build.

**Comment by karl-police** [comment] 2023-07-31 12:35
This is fixed now. #1166

**Comment by wilsontulus** [comment] 2023-08-04 23:35
Caused by guilty commit https://github.com/Epix-Incorporated/Adonis/commit/f0cb4ddd50f8fc6f1d51475bf2faa64fe374a4e9.
Probably submitted by a person who doesn't check Adonis fly scripts first, let alone his Adonis version, thus he just thought Adonis is still using BodyMovers while it's not used in latest versions.

**Closed** 2023-08-07 13:10 UTC
Labels: 🐛 bug
